#pragma once


enum TermColorStyle {
	STYLE_FG_DEFAULT,
	STYLE_BG_DEFAULT,
	STYLE_RESET,

	STYLE_FG_BLACK,
	STYLE_FG_RED,
	STYLE_FG_GREEN,
	STYLE_FG_YELLOW,
	STYLE_FG_BLUE,
	STYLE_FG_MAGENTA,
	STYLE_FG_CYAN,
	STYLE_FG_WHITE,

	STYLE_BG_BLACK,
	STYLE_BG_RED,
	STYLE_BG_GREEN,
	STYLE_BG_YELLOW,
	STYLE_BG_BLUE,
	STYLE_BG_MAGENTA,
	STYLE_BG_CYAN,
	STYLE_BG_WHITE,

	// Terminals supporting aixterm will support these styles
	STYLE_FG_BRIGHT_BLACK,
	STYLE_FG_BRIGHT_RED,
	STYLE_FG_BRIGHT_GREEN,
	STYLE_FG_BRIGHT_YELLOW,
	STYLE_FG_BRIGHT_BLUE,
	STYLE_FG_BRIGHT_MAGENTA,
	STYLE_FG_BRIGHT_CYAN,
	STYLE_FG_BRIGHT_WHITE,

	STYLE_BG_BRIGHT_BLACK,
	STYLE_BG_BRIGHT_RED,
	STYLE_BG_BRIGHT_GREEN,
	STYLE_BG_BRIGHT_YELLOW,
	STYLE_BG_BRIGHT_BLUE,
	STYLE_BG_BRIGHT_MAGENTA,
	STYLE_BG_BRIGHT_CYAN,
	STYLE_BG_BRIGHT_WHITE,
};
